# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA_DIR: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv

source_data:
  data_dir: data
  data_file: data.xml
